Feature/php8 support
nextapps-be/laravel-swagger-ui pull request #3
Opened 2021-02-11 12:33 UTC by jan-claeys

2021-02-12 09:44 UTC, yinx approved these changes

2021-02-12 10:28 UTC, gdebrauwer requested changes

2021-02-12 10:28 UTC, gdebrauwer commented on .github/workflows/run-tests.yml
> +                laravel: [ 8.*, 7.* ]
The package only supports Laravel 8 (see composer.json), so running the tests on Laravel 7 can be removed from atrix

2021-02-15 07:35 UTC, gdebrauwer approved these changes

2021-02-15 08:15 UTC, merged